version: "3.9"

networks:
  localhost:
    name: wtaylor

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: 
      context: ./requirements/Nginx
      # args:
      #   - DB_NAME
    image: nginx
    volumes:
      - wp:/var/www/
    ports:
      - "443:443"
    networks:
      - localhost
    # env_file:
    #   - .env
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: 
      context: ./requirements/Wordpress
      args:
        - DB_NAME
        - DB_HOST
        - DB_PASSWORD
        - DB_USER
    env_file:
      - .env
    image: wordpress
    volumes:
      - wp:/var/www/
    networks:
      - localhost
    restart: always
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - DB_NAME
        - DB_HOST
        - DB_PASSWORD
        - DB_USER
    image: mariadb
    volumes:
    - db:/var/lib/mariadb
    networks:
      - localhost
    env_file:
      - .env
    restart: always

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wtaylor/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wtaylor/data/wp