version: "3.9"

networks:
  localhost:
    name: wtaylor

services:
  nginx:
    container_name: nginx
    volumes:
      - wp:/var/www/
    build: 
      context: ./Nginx
      args:
        - DB_NAME
    image: nginx
    ports:
      - "443:443"
    networks:
      - localhost
    restart: always
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    volumes:
      - wp:/var/www/
    build: ./Wordpress
    image: wordpress
    networks:
      - localhost
    restart: always
  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: somewordpress
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: wordpress

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wp